server:
  port: 9099  # ????
spring:
  application:
    name: tiktok-user  # ????????? Nacos

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  # Nacos ???????
        namespace: public  # ???????
      config:
        import-check-enabled: false  # ????????