server:
  port: 8083
spring:
  main:
    web-application-type: reactive
  application:
    name: tiktok-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: public
      config:
        import-check-enabled: false



