server:
  port: 9092  # 服务端口
spring:
  application:
    name: tiktok-cart  # 服务名，用于注册到 Nacos

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848  # Nacos 注册中心的地址
        namespace: public  # 可选，命名空间
      config:
        import-check-enabled: false  # 禁用配置导入检查
